### ISSUE TITLE
air started but NOT reloading

### ISSUE THREAD

**Issue by kockok** [cosmtrek/air#274] opened 2022-05-08 09:53 UTC
<img width="850" alt="Screenshot 2022-05-08 at 5 44 13 PM" src="https://user-images.githubusercontent.com/232541/167290762-f3a5186d-685f-433c-a7c5-27760c205784.png">

It seems to be working, but there's no rebuilding after I change the code.

Dockerfile:
```
FROM golang:alpine
RUN apk add --no-cache git
WORKDIR /app
COPY go.* .
COPY *air.toml .
RUN go mod download
COPY . .
RUN go install github.com/cosmtrek/air@latest
CMD ["air", "-c", ".air.toml"]
```

docker-copose.yml
```
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/test?authSource=admin

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb

volumes:
  mongo:
```

I'm using M1 macbook, just wondering if it's an ARM/AMD thing.

**Comment by badcc** [comment] 2022-05-15 23:33
I am also experiencing this... on Intel.. I wonder if related to a new version of Docker or something? Maybe fsnotify somehow not working with mounted volumes? Will continue looking but thought I'd post here to show support..

**Comment by kockok** [comment] 2022-05-16 04:23
> I am also experiencing this... on Intel.. I wonder if related to a new version of Docker or something? Maybe fsnotify for some particular reason/stack not working with mounted volumes? Will continue looking but thought I'd post here to show support. Works fine locally, without Docker.
> 
> EDIT: Seems potentially related from mounted volumes on Docker for Windows/WSL not firing the necessary I/O events.. can anyone else confirm?
> 
> EDIT2: The real issue is here [microsoft/WSL#4739](https://github.com/microsoft/WSL/issues/4739) and I was able to resolve my problem by integrating Docker with my Ubuntu WSL2 distro, and putting my file system in the Linux-mounted \wsl$ file system. Now fsnotify is properly detecting changes, and Air works!

Good for you, if it's not an ARM thing, then I'll wait for Air to get updated :)

**Comment by ctiller15** [comment] 2022-08-01 14:06
Checking in - @kockok did you ever find a resolution for this? I'm running into the exact same problem setting up air to run w/ docker on my M1.

**Comment by kockok** [comment] 2022-08-03 05:35
> Checking in - @kockok did you ever find a resolution for this? I'm running into the exact same problem setting up air to run w/ docker on my M1.

Negative, I switched to `CompileDaemon` tentatively, but really want air instead...

**Comment by ctiller15** [comment] 2022-08-04 15:33
> > Checking in - @kockok did you ever find a resolution for this? I'm running into the exact same problem setting up air to run w/ docker on my M1.
> 
> Negative, I switched to `CompileDaemon` tentatively, but really want air instead...

Gotcha. Is there an existing issue that addresses this? If not shouldn't this one be reopened?

**Comment by windowshopr** [comment] 2022-08-07 07:03
I'm new to Go, but I'm having the same problem.

`Windows 10, Go 1.19, AMD`

My simple sample project structure and code looks like this:

![image](https://user-images.githubusercontent.com/40477419/183279230-b6333876-36e3-4f65-b35e-21f7185121db.png)

...which results in a simple page that looks like this:

![image](https://user-images.githubusercontent.com/40477419/183279243-2cb1d0ee-90bb-4d27-9145-e36e0f9f48a8.png)

So I go to make a change in `main.go`, like changing hello world to something else and save:

![image](https://user-images.githubusercontent.com/40477419/183279287-ed80d1f6-302a-4922-972b-0ecc55a3764b.png)

...but the terminal output doesn't change at all, like Air SAYS it's "watching" for changes, but when I save, nothing happens in the output.

So then, even after clearing browser cache, and using a new incognito window, the change doesn't even reflect on the page:

![image](https://user-images.githubusercontent.com/40477419/183279341-90e110e6-9fb0-4f92-a17a-3516d6ee84bb.png)

Forgive my newbie-ness, but what's happening here?

**Comment by windowshopr** [comment] 2022-08-08 06:28
One thing that might be worth mentioning here is that I’m running this inside a docker-compose. Maybe it doesn’t apply changes saved in a container, but only on local instances of the app?

**Comment by badcc** [comment] 2022-08-08 16:05
I'm fairly confident that the issue is due to `fsnotify` not picking up file system events between the Linux/Ubuntu Docker file system  (LFTS), and the Windows file system (NFTS) which is making the changes through the mounted volume (such as.. through VSCode/etc.). I believe the only good solution is for `air` to implement polling... so until then, as @kockok has done, I have switched to `CompileDaemon` (or similar) which offers polling.

(Or, fsnotify could add polling themselves, but this has been open since 2014: https://github.com/fsnotify/fsnotify/issues/9#issue-36736290)

Thus, this issue is better closed in favor of/described by #190 (or the earlier, but less discussed, #67).

**Comment by ShayperCool** [comment] 2022-10-05 18:50
Just noticed my Docker Desktop in Linux use virtiofs in container, so I tried disable it thourgh "~/.docker/desktop/settings.json" setting "useVirtualizationFrameworkVirtioFS": true -> "useVirtualizationFrameworkVirtioFS": false. After that Docker Desktop stop running. And I just installed usual docker :), and now hot reload is working.
So, maybe in Windows or Mac you can change this parameter and Docker Desktop will run, and you maybe will get working hot reload, but I can't test it myself.

**Comment by azmiadhani** [comment] 2023-01-11 06:58
> Just noticed my Docker Desktop in Linux use virtiofs in container, so I tried disable it thourgh "~/.docker/desktop/settings.json" setting "useVirtualizationFrameworkVirtioFS": true -> "useVirtualizationFrameworkVirtioFS": false. After that Docker Desktop stop running. And I just installed usual docker :), and now hot reload is working. So, maybe in Windows or Mac you can change this parameter and Docker Desktop will run, and you maybe will get working hot reload, but I can't test it myself.

I tried this. Unfortunately does not work, after I set ```useVirtualizationFrameworkVirtioFS:false``` docker always failed to start.

**Comment by azmiadhani** [comment] 2023-01-12 00:28
Updating Docker Engine to the latest version seems to solve the issues with air to me. 
![image](https://user-images.githubusercontent.com/13920914/211946746-fe9c48e9-5962-4b18-bc37-26577671bc01.png)
![image](https://user-images.githubusercontent.com/13920914/211947237-3ab5088c-8856-4bdd-b781-70bdb6a3e6cf.png)

**Comment by subkaitaku** [comment] 2023-01-21 04:15
I tried both versions and neither detected a difference.
macOS: 13.1
M1 MacBook

```
Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
```

```
Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
```

**Comment by azmiadhani** [comment] 2023-01-21 10:42
Sorry to hear that. By the way, this is my `docker-compose.yaml` file just in case anyone needs it.
![image](https://user-images.githubusercontent.com/13920914/213863289-9b53392f-50dc-433b-b564-901a9cb1d338.png)
Also, this is my `Dockerfile`.
![image](https://user-images.githubusercontent.com/13920914/213863306-c766d445-56f7-467b-99f3-df00023d9b35.png)

**Comment by devmeireles** [comment] 2023-01-25 18:47
I'm facing the same issue in Windows 11 on Docker v20.10.22

**Comment by kaspers1778** [comment] 2023-02-19 16:18
WIndows 10, Docker v20.10.22, ditto. Working if run air from terminal, not working if run it from docker compose.

**Comment by CoolGoose** [comment] 2023-02-19 22:10
Unfortunately, I have the same problem.
Initial build works, but no luck getting anything updated.

```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2020-‎08-‎23
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0
```
```
Docker Engine
v20.10.22
```

.air.toml
```
[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "tmp/api"
```

docker-compose.yml
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: air
    ports:
      - 8080:8080
    volumes:
      - ./:/app
```

**Comment by edegp** [comment] 2023-03-02 15:31
I had same issue but only forget docker-compose a volume-mount setting .
```yaml: docker-comopse.yml
web:
    container_name: go_app
    volumes:
       ...
      - ./app:/app  #← add this
```
`dockerfile` in root and `air.toml` in app directory

**Comment by NicholasKoldys** [comment] 2023-05-06 14:23
VScode alternative solution is to use Dev Container and Docker Extensions (by Microsoft.com).

Connect to the container via instructions provided by Dev Container and navigate to the working directory through the explorer (you may be defaulted to /root/) and file changes will reload with Air.

With the volume type mount, I haven't seen any issues arise, however, working on the host vscode window, there seems to be no response with file changes in Air.

note: vscode dev container instance will not have your extensions.

**Comment by wassimbj** [comment] 2023-07-14 08:22
I'm on windows, i thought it may be a permission issue, so i started vscode and docker as administrator, but no luck. the only solution i found was to make air to use polling instead of events, so what you should do is basically change poll to true and it should work
```toml
# Poll files for changes instead of using fsnotify.
poll = true
```

**Comment by arun-art06** [comment] 2023-07-18 15:16
> I'm on windows, i thought it may be a permission issue, so i started vscode and docker as administrator, but no luck. the only solution i found was to make air to use polling instead of events, so what you should do is basically change poll to true and it should work
> 
> ```toml
> # Poll files for changes instead of using fsnotify.
> poll = true
> ```

Excellent answer. It works for me. 

**i have just changed in the .air.toml
[build]
    poll = true**

**Comment by swarajkumarsingh** [comment] 2023-10-07 05:24
# The perfect solution 💕

**Issue:** Air is starting but not reloading on changes in the project

**Solution:** In .air.toml file add _poll = true_ This is because Windows has some restrictions and to overcome that we set poll to true

**Solution in code:** 
```
poll = true
```

**Comment by xiantang** [comment] 2023-10-19 17:12
I think it's solved

**Closed by xiantang** 2023-10-19 17:12 UTC

**Comment by XiaoxiaYao** [comment] 2023-10-26 22:18
It's the docker issue for me. Just updat to the latest docker app.

**Comment by zhitoo** [comment] 2023-11-02 16:03
> I'm new to Go, but I'm having the same problem.
> 
> `Windows 10, Go 1.19, AMD`
> 
> My simple sample project structure and code looks like this:
> 
> ![image](https://user-images.githubusercontent.com/40477419/183279230-b6333876-36e3-4f65-b35e-21f7185121db.png)
> 
> ...which results in a simple page that looks like this:
> 
> ![image](https://user-images.githubusercontent.com/40477419/183279243-2cb1d0ee-90bb-4d27-9145-e36e0f9f48a8.png)
> 
> So I go to make a change in `main.go`, like changing hello world to something else and save:
> 
> ![image](https://user-images.githubusercontent.com/40477419/183279287-ed80d1f6-302a-4922-972b-0ecc55a3764b.png)
> 
> ...but the terminal output doesn't change at all, like Air SAYS it's "watching" for changes, but when I save, nothing happens in the output.
> 
> So then, even after clearing browser cache, and using a new incognito window, the change doesn't even reflect on the page:
> 
> ![image](https://user-images.githubusercontent.com/40477419/183279341-90e110e6-9fb0-4f92-a17a-3516d6ee84bb.png)
> 
> Forgive my newbie-ness, but what's happening here?

i have this problem just quite terminal and run air command again.

**Comment by swarajkumarsingh** [comment] 2023-11-02 17:18
> > I'm new to Go, but I'm having the same problem.
> > 
> > `Windows 10, Go 1.19, AMD`
> > 
> > My simple sample project structure and code looks like this:
> > 
> > ![image](https://user-images.githubusercontent.com/40477419/183279230-b6333876-36e3-4f65-b35e-21f7185121db.png)
> > 
> > ...which results in a simple page that looks like this:
> > 
> > ![image](https://user-images.githubusercontent.com/40477419/183279243-2cb1d0ee-90bb-4d27-9145-e36e0f9f48a8.png)
> > 
> > So I go to make a change in `main.go`, like changing hello world to something else and save:
> > 
> > ![image](https://user-images.githubusercontent.com/40477419/183279287-ed80d1f6-302a-4922-972b-0ecc55a3764b.png)
> > 
> > ...but the terminal output doesn't change at all, like Air SAYS it's "watching" for changes, but when I save, nothing happens in the output.
> > 
> > So then, even after clearing browser cache, and using a new incognito window, the change doesn't even reflect on the page:
> > 
> > ![image](https://user-images.githubusercontent.com/40477419/183279341-90e110e6-9fb0-4f92-a17a-3516d6ee84bb.png)
> > 
> > Forgive my newbie-ness, but what's happening here?
> 
> i have this problem just quite terminal and run air command again. 

Try changing your browser or just follow my  solution

**Comment by masonbesmer** [comment] 2023-12-18 21:46
Polling is not a performant solution. What is the underlying issue here?

I have tested on Arch and Windows and both platforms suffer from the same issue.

`[mason@mason-surfarch ~]$ docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        afdd53b4e3
 Built:             Sun Oct 29 15:42:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       311b9ff0aa
  Built:            Sun Oct 29 15:42:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.11
  GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba.m
 runc:
  Version:          1.1.10
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[mason@mason-surfarch ~]$ uname -a
Linux mason-surfarch 6.6.6-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Wed, 13 Dec 2023 21:27:25 +0000 x86_64 GNU/Linux
[mason@mason-surfarch ~]$`

**Comment by merbekta** [comment] 2024-02-22 12:07
> # The perfect solution 💕
> **Issue:** Air is starting but not reloading on changes in the project
> 
> **Solution:** In .air.toml file add _poll = true_ This is because Windows has some restrictions and to overcome that we set poll to true
> 
> **Solution in code:**
> 
> ```
> poll = true
> ```

it works for me

**Comment by swarajkumarsingh** [comment] 2024-02-28 04:06
> Polling is not a performant solution. What is the underlying issue here?
> 
> I have tested on Arch and Windows and both platforms suffer from the same issue.
> 
> > [mason@mason-surfarch ~]$ docker version
> > Client:
> > Version:           24.0.7
> > API version:       1.43
> > Go version:        go1.21.3
> > Git commit:        afdd53b4e3
> > Built:             Sun Oct 29 15:42:02 2023
> > OS/Arch:           linux/amd64
> > Context:           default
> 
> > Server:
> > Engine:
> > Version:          24.0.7
> > API version:      1.43 (minimum version 1.12)
> > Go version:       go1.21.3
> > Git commit:       311b9ff0aa
> > Built:            Sun Oct 29 15:42:02 2023
> > OS/Arch:          linux/amd64
> > Experimental:     false
> > containerd:
> > Version:          v1.7.11
> > GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba.m
> > runc:
> > Version:          1.1.10
> > GitCommit:
> > docker-init:
> > Version:          0.19.0
> > GitCommit:        de40ad0
> > [mason@mason-surfarch ~]$ uname -a
> > Linux mason-surfarch 6.6.6-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Wed, 13 Dec 2023 21:27:25 +0000 x86_64 GNU/Linux
> > [mason@mason-surfarch ~]$

Yes, polling is not the best option, but as long as we are only using air for development, it is acceptable. Air does not use additional memory, but it does make reloading somewhat slower, which is fine for development purposes. Perhaps this issue will be resolved later.

**Comment by benjaminyakobi** [comment] 2024-05-30 19:43
> I'm on windows, i thought it may be a permission issue, so i started vscode and docker as administrator, but no luck. the only solution i found was to make air to use polling instead of events, so what you should do is basically change poll to true and it should work
> 
> ```toml
> # Poll files for changes instead of using fsnotify.
> poll = true
> ```

God bless you, thanks!

**Comment by piru72** [comment] 2025-01-27 10:35
Is anyone still facing this issue? My live reloading is still not working.

OS: `Windows 11 Pro 24H2`
Docker Desktop version: `Docker Desktop 4.37.1 (178610)`
Air version : `@latest`
```Dockerfile

# winners-crud/server/Dockerfile

FROM golang:latest
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY server/go.mod server/go.sum ./
RUN go mod download
COPY ./server .
RUN go build -o main .
EXPOSE 4000
CMD ["air"]
```

```docker-compose.yml

# winners-crud/docker-compose.yml
server:
    container_name: winner-crud-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - '4000:4000'
    command: air
```
Have made `poll=true`

```air.toml
# winners-crud/server/air.toml
# taken from https://blog.logrocket.com/using-air-go-implement-live-reload/
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  poll = true
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
```

**Comment by swarajkumarsingh** [comment] 2025-01-28 11:59
Can you please share the logs

**Comment by piru72** [comment] 2025-01-28 12:11
This is my logs , 
```logs
2025-01-28 18:07:58 
2025-01-28 18:07:58   __    _   ___  
2025-01-28 18:07:58  / /\  | | | |_) 
2025-01-28 18:07:58 /_/--\ |_| |_| \_ v1.61.7, built with Go go1.23.5
2025-01-28 18:07:58 
2025-01-28 18:07:58 watching .
2025-01-28 18:07:58 watching bin
2025-01-28 18:07:58 watching config
2025-01-28 18:07:58 watching database
2025-01-28 18:07:58 watching database/entities
2025-01-28 18:07:58 watching database/repositories
2025-01-28 18:07:58 watching handlers
2025-01-28 18:07:58 watching handlers/v1
2025-01-28 18:07:58 watching routes
2025-01-28 18:07:58 watching routes/v1
2025-01-28 18:07:58 watching services
2025-01-28 18:07:58 !exclude tmp
2025-01-28 18:07:58 watching utils
2025-01-28 18:07:58 building...
2025-01-28 18:08:25 go: downloading github.com/gofiber/fiber/v2 v2.52.6
2025-01-28 18:08:25 go: downloading github.com/google/uuid v1.6.0
2025-01-28 18:08:25 go: downloading github.com/valyala/bytebufferpool v1.0.0
2025-01-28 18:08:25 go: downloading github.com/valyala/fasthttp v1.58.0
2025-01-28 18:08:25 go: downloading github.com/mattn/go-runewidth v0.0.16
2025-01-28 18:08:25 go: downloading github.com/mattn/go-colorable v0.1.14
2025-01-28 18:08:25 go: downloading github.com/rivo/uniseg v0.4.7
2025-01-28 18:08:25 go: downloading golang.org/x/sys v0.29.0
2025-01-28 18:08:25 go: downloading github.com/andybalholm/brotli v1.1.1
2025-01-28 18:08:25 go: downloading github.com/klauspost/compress v1.17.11
2025-01-28 18:08:25 go: downloading github.com/valyala/tcplisten v1.0.0
2025-01-28 18:08:25 running...
2025-01-28 18:08:26 Serving on port 4000...
2025-01-28 18:08:26 
2025-01-28 18:08:26  ┌───────────────────────────────────────────────────┐ 
2025-01-28 18:08:26  │                   Fiber v2.52.6                   │ 
2025-01-28 18:08:26  │               http://127.0.0.1:4000               │ 
2025-01-28 18:08:26  │       (bound on host 0.0.0.0 and port 4000)       │ 
2025-01-28 18:08:26  │                                                   │ 
2025-01-28 18:08:26  │ Handlers ............ 12  Processes ........... 1 │ 
2025-01-28 18:08:26  │ Prefork ....... Disabled  PID ............... 618 │ 
2025-01-28 18:08:26  └───────────────────────────────────────────────────┘ 
2025-01-28 18:08:26
```

I have changed my `air.toml` the current one is

**Comment by Hugzerr** [comment] 2025-05-18 21:11
In case it can help, I fixed it with poll=true with the bookworm version first but then switch my go container to the **alpine** one and it works even without the polling (you just have to change use apk instead of apt-get and you're good to go).
