### ISSUE TITLE
Error /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by benc-uk** [cosmtrek/air#427] opened 2023-05-20 15:58 UTC
I've been using `air` for years on my system, today I downloaded the latest version and I get this error

```
./air_1.43.0_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./air_1.43.0_linux_amd64)
./air_1.43.0_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./air_1.43.0_linux_amd64)
```

I am running Ubuntu 20.04 LTS

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by benc-uk** [comment] 2023-05-20 15:59
I rolled back to 1.42.0 of `air` and the error was gone
Something big changed with the 1.43.0 release or build

**Comment by benc-uk** [comment] 2023-05-22 08:16
Seems like this was caused by the recent version bump to 1.20
https://github.com/golang/go/issues/58550

**Comment by hotrush** [comment] 2023-05-30 14:12
Adding `apt install -y libc6 libc6-dev libc6-dbg` helped to me

**Comment by mstgnz** [comment] 2023-06-02 08:50
Same problem
`air: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by air)`

**Comment by silverwind** [comment] 2023-06-05 17:34
Duplicate of https://github.com/cosmtrek/air/issues/415.

**Comment by xiantang** [comment] 2023-10-09 16:39
close for dupl

**Closed by xiantang** 2023-10-09 16:39 UTC
