### ISSUE TITLE
Process tracking can get off-by-one

### ISSUE THREAD

**Issue by arya** [cosmtrek/air#94] opened 2020-07-29 15:57 UTC
I've observed that sometimes `air` fails to kill the previous version of the process and tries to start a new one and fails. Here is a log with the debug flag on:

```
make[1]: Entering directory '/app/go'
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": WRITE
api-server/app/auth/auth.go has changed
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": WRITE
api-server/app/auth/auth.go has changed
flushing events
api-server/app/auth/auth.go has changed
make[1]: Leaving directory '/app/go'
running...
[GIN-debug] Listening and serving HTTP on :8080
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": WRITE
api-server/app/auth/auth.go has changed
api-server/app/auth/auth.go has changed
building...
trying to kill cmd [/bin/sh -c bin/api-server]
cmd killed, pid: 274
make[1]: Entering directory '/app/go'
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": WRITE
api-server/app/auth/auth.go has changed
event: "/app/go/api-server/app/auth/auth.go": CHMOD
event: "/app/go/api-server/app/auth/auth.go": WRITE
api-server/app/auth/auth.go has changed
flushing events
api-server/app/auth/auth.go has changed
building...
make[1]: Entering directory '/app/go'
make[1]: Leaving directory '/app/go'
running...
[GIN-debug] Listening and serving HTTP on :8080
make[1]: Leaving directory '/app/go'
running...
[GIN-debug] Listening and serving HTTP on :8080
[GIN-debug] [ERROR] listen tcp :8080: bind: address already in use
```

**Comment by jhartman86** [comment] 2020-09-12 20:04
Major +1 for this issue. I see this issue _all the time_, to the point where AIR is basically unusable and requires stopping/restarting the air process entirely... at which point, what's the point.

**Comment by xiantang** [comment] 2020-09-13 05:13
> Major +1 for this issue. I see this issue _all the time_, to the point where AIR is basically unusable and requires stopping/restarting the air process entirely... at which point, what's the point.

can you provider more informations about this issue. such as os platform

**Comment by jhartman86** [comment] 2020-09-14 19:14
@xiantang can't speak for original poster, but I see this on Alpine Linux (ie. inside a Docker container) all the time. It'll work for about 10 or so minutes before AIR seems like it loses track of which processes are running or not, then starts trying to build/run the latest prior to the other process having fully shutdown (or trying to shutdown at all).

**Comment by arya** [comment] 2020-09-14 19:27
I'm on macOS running docker.

**Comment by naseem-opal** [comment] 2020-10-14 04:15
I am also seeing this issue, but more or less immediately on MacOS not using Docker.

**Comment by technicallyjosh** [comment] 2020-10-26 22:50
I ran into this issue all the time on OSX inside docker-compose. I fixed it by adding the following to a `.air.toml` file...

```toml
[build]
kill_delay = 1000
```

**Comment by silverwind** [comment] 2020-11-15 23:22
Happens regularily here as well. Sometimes, when saving files in quick succession, Air seems to fail to kill of the old process which then get orphaned and the only remedy is to stop watching and `kill` it.

**Comment by Dids** [comment] 2020-11-24 08:12
Could this potentially be remedied by always having the `delay` option be greated than `kill_delay`, to ensure that the process is killed before even attempting to trigger a new build?

In my case I'm relying on `send_interrupt` instead, so `kill_delay` should ideally never kick in, but I'm still seeing all sorts of weird behavior, such as the process getting killed before it has gracefully shut down, even though the `kill_delay` hasn't been reached yet.
My theory regarding this particular issue is that it's caused by new changes/builds triggering in quick succession, while the "kill timer" is still running for the original process, which ends up killing the wrong process effectively.

**Comment by mrsufgi** [comment] 2022-02-01 15:50
happening for me too, but off by two (2), Mac M1pro within a docker container with dlv

**Comment by xiantang** [comment] 2022-02-22 15:21
fixed in v1.29.0

**Closed by xiantang** 2022-02-22 15:21 UTC
